Revert "base: add API for disabling gestural navigation"
frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/CommandQueue.java:1953: error: duplicate case label
                case MSG_ENTER_DESKTOP: {
                ^
1 error

* skill issue on my side

This reverts commit 7a3ecccdb165959482da58c255f759b30976b413.